### ISSUE TITLE
some site requests.get() return ConnectionError

### ISSUE THREAD

**Issue by shizhao** [xhacker/miracle-board#10]
some site requests.get() return ConnectionError

requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",

also, requests.get("http://www.sciencedirect.com/"), no response

Recommended urllib2

**Comment by gdude2002** [comment]
This has nothing to do with miracle-board. 

That said, requests is infinitely better than urllib. Urllib is not an HTTP library, it is a generic URL-handling library. 

Requests is failing here because that is the correct thing to do.

**Comment by xhacker** [comment]
If requests has something that feels wrong to you, can you file an issue with requests instead? Thank you!
