### ISSUE TITLE
Parallel Pinging

### ISSUE THREAD

**Issue by ralgozino** [xhacker/miracle-board#7]
It would be great if the pings check could be done in parallel.

Right now if several servers are down, it takes a lot to finish the check.

**Comment by xhacker** [comment]
It's already parallel isn't it? The frontend is making multiple ajax calls at the same time.

**Comment by ralgozino** [comment]
Hello! Not in my case. Using the development flask server and latest Chrome / Firefox. Let's say a server is down, I can see the hourglass in the next servers until the timeout occurs...

**Comment by xhacker** [comment]
It's because of the development server is single-threaded. In production, you can set the server to have more concurrent workers.

**Comment by ralgozino** [comment]
aw, I see. thanks a lot! :) great software you've maid, was exactly what I was looking for (with some minor tweaks).

Cheers!
